name: Daily Heartbeat

on:
  schedule:
    - cron: "0 10 * * *"   # Runs 10:00 UTC daily (≈ 6am ET during DST)
  workflow_dispatch:        # Allow manual run

permissions:
  contents: write           # Needed so the workflow can push

jobs:
  beat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make a tiny change (append timestamp)
        run: |
          echo "$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> .keep

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily heartbeat"
          file_pattern: ".keep"
          commit_user_name: "Prashanth Madishetti"
          commit_user_email: "230023683+PrashanthMadishetti@users.noreply.github.com"
          branch: main
